use LMS;

create table FellowshipCandidate(
Candidate_ID int auto_increment PRIMARY KEY,
CIC_ID int,
FirstName varchar(225),
MiddleName varchar(225),
LastName varchar(225),
EmailId  varchar(225),
HiredCity varchar(225),
Degree  varchar(225),
HiredDate date,
Mobile_Number bigint,
Permanent_Pincode int,
HiredLab varchar(225),
Attitde varchar(225),
Communication_Remark varchar(225),
Knownledge_Remark varchar(225),
Aggregate_Remark int,
Creator_Stamp date,
Creator_User varchar(225),
BirthDate date,
Is_Birth_Date_Verfied bit,
Parent_Name varchar(225),
Parent_Occupation varchar(225),
Parents_Mobilenumber bigint,
Parents_Annual_Salary bigint,
LocalAddress varchar(225),
Permanent_Address varchar(225),
Photo_Path varchar(225),
Joining_Date date, 
Candidate_Status varchar(225),
Personal_Information varchar(225),
Bank_Information varchar(225),
Educational_Information varchar(225),
Document_Status varchar(225),
Remark varchar(225)
 );
